<?php

/*
 +-----------------------------------------------------------------------+
 |                                                                       |
 | Language file of the Roundcube jappix4roundcube plugin                |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Remi Dionisi  <Unknown>                                       |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['jappixUsername'] = 'Uživatel';
$labels['jappixDomain'] = 'Doména';
$labels['jappixPassword'] = 'Heslo';
$labels['jappixSection'] = 'XMPP';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Správa Jappix';

