<?php

/*
 +-----------------------------------------------------------------------+
 |                                                                       |
 | Language file of the Roundcube jappix4roundcube plugin                |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Remi Dionisi  <Unknown>      thaks to reiner.buehl            |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['jappixUsername'] = 'Benutzer (leer lassen, um Jappix abzuschalten)';
$labels['jappixDomain'] = 'Domäne';
$labels['jappixPassword'] = 'Passwort';
$labels['jappixSection'] = 'XMPP';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Jappix konfigurieren';