<?php

/*
 +-----------------------------------------------------------------------+
 |                                                                       |
 | Language file of the Roundcube jappix4roundcube plugin                |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Remi Dionisi  <Unknown>                                       |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['jappixUsername'] = 'User (leave empty to disable)';
$labels['jappixDomain'] = 'Domaine';
$labels['jappixPassword'] = 'Password';
$labels['jappixDisable'] = 'Disable';
$labels['jappixSection'] = 'XMPP';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Manage Jappix';

