<?php

/*
 +-----------------------------------------------------------------------+
 |                                                                       |
 | Language file of the Roundcube jappix4roundcube plugin                |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Rémi Dionisi  <Unknown>                                       |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['jappixUsername'] = 'Utilisateur';
$labels['jappixDomain'] = 'Domaine';
$labels['jappixPassword'] = 'Mot de passe';
$labels['jappixSection'] = 'XMPP';
