<?php

/*
 +-----------------------------------------------------------------------+
 |                                                                       |
 | Language file of the Roundcube jappix4roundcube plugin                |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Remi Dionisi  <Unknown>      thaks to marco.buzzotta          |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['jappixUsername'] = 'Nome Utente';
$labels['jappixDomain'] = 'Dominio';
$labels['jappixPassword'] = 'Password';
$labels['jappixSection'] = 'XMPP';
$labels['task'] = 'Chat';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Amministra Jappix';