<?php

/*
 +-----------------------------------------------------------------------+
 |                                                                       |
 | Language file of the Roundcube jappix4roundcube plugin                |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Remi Dionisi  <Unknown>                                       |
 +-----------------------------------------------------------------------+
 @version $Id$
*/

$labels = array();
$labels['jappixUsername'] = 'Логин (оставльте пустым, чтобы отключить)';
$labels['jappixDomain'] = 'Домен';
$labels['jappixPassword'] = 'Пароль';
$labels['jappixSection'] = 'XMPP';
$labels['task'] = 'Чат';
$labels['title'] = 'Jappix';
$labels['manager'] = 'Управление Jappix';

